### ISSUE TITLE
Error on usage

### ISSUE THREAD

**Issue by brundonsmith** [jed/esbuild-plugin-http-fetch#5]
Hi! I don't know if this is still maintained, but I have an issue when I try to use it:
```typescript
const esbuild = await import("https://raw.githubusercontent.com/esbuild/deno-esbuild/main/mod.js")
const httpFetch = await import("https://deno.land/x/esbuild_plugin_http_fetch@v1.0.3/index.js") as any

try {
    await esbuild.build({
        plugins: [ httpFetch ],
        write: true,
        bundle: true,
        minify: false,
        entryPoints: [ entryFile ],
        outfile,
    })
    
    ...
```
    
When I run the above, I get:
```
 > error: Plugin at index 0 is missing a name

Error: Build failed with 1 error:
error: Plugin at index 0 is missing a name
    at failureErrorWithLog (https://raw.githubusercontent.com/esbuild/deno-esbuild/main/mod.js:1439:15)
    at https://raw.githubusercontent.com/esbuild/deno-esbuild/main/mod.js:982:18
    at https://raw.githubusercontent.com/esbuild/deno-esbuild/main/mod.js:977:9
    at https://raw.githubusercontent.com/esbuild/deno-esbuild/main/mod.js:573:9
    at handleIncomingPacket (https://raw.githubusercontent.com/esbuild/deno-esbuild/main/mod.js:670:9)
    at readFromStdout (https://raw.githubusercontent.com/esbuild/deno-esbuild/main/mod.js:540:7)
    at https://raw.githubusercontent.com/esbuild/deno-esbuild/main/mod.js:1709:11
```
    
  Any help would be appreciated

**Comment by brundonsmith** [comment]
I figured out that if I import it non-dynamically, it works. I was then able to get it working dynamically like so:
```typescript
const httpFetch = (await import("https://deno.land/x/esbuild_plugin_http_fetch@v1.0.3/index.js")).default
```
